# ファイル名: .github/workflows/daily_download_count.yml
# Written By ChatGPT
name: Daily GitHub Release Download Count

permissions:
  contents: write

on:
  schedule:
    - cron: '0 9 * * *' # 毎日 9:00 UTC (18:00 JST) に実行
  workflow_dispatch: # 手動実行用

jobs:
  fetch-downloads:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run script
        run: python get_release_downloads.py

      - name: Commit and push CSV
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add GitHubDownloads.csv
          git commit -m "Update download counts"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
